// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bottom: string;
  cartList: string;
  grid: string;
  gridItem: string;
  gridTitle: string;
  image: string;
  imageItem: string;
  items: string;
  name: string;
  nameItem: string;
  nameTitle: string;
  price: string;
  priceItem: string;
  priceTitle: string;
  quantity: string;
  quantityBox: string;
  quantityButton: string;
  quantityInput: string;
  quantityItem: string;
  quantityTitle: string;
  quantityUpdate: string;
  remove: string;
}
export const cssExports: CssExports;
export default cssExports;
