// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom': string;
  'grid': string;
  'gridItem': string;
  'image': string;
  'imageItem': string;
  'items': string;
  'name': string;
  'nameItem': string;
  'nameTitle': string;
  'price': string;
  'priceItem': string;
  'priceTitle': string;
  'quantity': string;
  'quantityButton': string;
  'quantityInput': string;
  'quantityItem': string;
  'quantityTitle': string;
  'quantityUpdate': string;
  'remove': string;
}
export const cssExports: CssExports;
export default cssExports;
