// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  button: string;
  content: string;
  grandTotal: string;
  price: string;
  priceLarge: string;
  subtotal: string;
  summary: string;
  text: string;
  titleSection: string;
  total: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
