// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'grandTotal': string;
  'price': string;
  'subtotal': string;
  'summary': string;
  'summaryContent': string;
  'text': string;
  'titleSection': string;
}
export const cssExports: CssExports;
export default cssExports;
